[package]
name = "tlockr"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.5"
nix = { version = "0.30.1", features = [ "fs" ] }
wayland-client = "0.31.10"
wayland-protocols = { version = "0.32.8", features = [ "client", "staging" ] }
xkbcommon-rs = "0.1.2"
