name: CI

on:
    push:
        branches: ["main"]
        paths:
            - "build.rs"
            - "Cargo.toml"
            - "Cargo.lock"
            - "CMakeLists.txt"
            - "cpp/**"
            - "src/**"
            - "test/**"
    pull_request:
        branches: ["main"]
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
            - "build.rs"
            - "Cargo.toml"
            - "Cargo.lock"
            - "CMakeLists.txt"
            - "cpp/**"
            - "src/**"
            - "test/**"
    merge_group:
        types: [checks_requested]

permissions:
    contents: read
    pull-requests: read

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        name: "Build and Test"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install -y \
                    qt6-base-dev qt6-declarative-dev qt6-tools-dev \
                    qt6-base-dev-tools libgl1-mesa-dev libxkbcommon-dev \
                    llvm-dev libclang-dev clang libpam0g-dev

            - name: Configure environment
              run: echo "QT6_PREFIX=$(qtpaths6 --install-prefix)" >> $GITHUB_ENV

            - name: Build
              env:
                  CMAKE_PREFIX_PATH: ${{ env.QT6_PREFIX }}
              run: |
                  cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DRUST_VERBOSE=ON
                  cmake --build build
                  
            - name: Test
              run: ctest --test-dir build --output-on-failure
