name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        types: [opened, synchronize, reopened, ready_for_review]

permissions:
    contents: read
    pull-requests: read

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        name: "Build and Test"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install -y \
                    qt6-base-dev qt6-declarative-dev qt6-tools-dev \
                    qt6-base-dev-tools libgl1-mesa-dev

            - name: Configure environment
              run: echo "QT6_PREFIX=$(qtpaths6 --install-prefix)" >> $GITHUB_ENV

            - name: Build
              env:
                  CMAKE_PREFIX_PATH: ${{ env.QT6_PREFIX }}
              run: cargo build --verbose

            - name: Test
              run: cargo test --verbose
